### ISSUE TITLE
请教方案

### ISSUE THREAD

**Issue by rayyzhong** [xiaoyun94/weapp-java-tunnel-demo#2]
请教大力哥，阅读你博客和代码收益匪浅，请教现在如果做微信小程序，什么方案做socket连接你觉得是最好的？

**Comment by xiaoyun94** [comment]
腾讯爸爸都给你做好解决方案了，如果你是使用腾讯云的解决方案，事情会特别简单，只需要专心应用程序开发就好了，SOCKET管道都是已经现成的了。我这个只是代替腾讯云的信道服务器。当然给予SOCKET的应用层面的协议设计就靠自己了

**Comment by rayyzhong** [comment]
好的，非常感谢，还是用爸爸的Tunnel吧

**Comment by xiaoyun94** [comment]
即使用了爸爸的服务，但是协议还是要来自己做的。这个东西只是提供给不想给爸爸交钱的人像我这种穷鬼做的
